// src/components/blog/DataTable.tsx
import { useMemo, useState } from "react";
import { formatNumber } from "./chartData";

export interface DataColumn {
	key: string;
	label: string;
	align?: "left" | "right" | "center";
	/** Treat values as numbers for sorting + default right-alignment. */
	numeric?: boolean;
	format?: (value: string | number) => string;
}

export type DataRow = Record<string, string | number>;

interface DataTableProps {
	columns: DataColumn[];
	rows: DataRow[];
	caption?: string;
	sortable?: boolean;
	compact?: boolean;
	/** Drop the outer card chrome (used when embedded under a chart). */
	bare?: boolean;
}

type SortState = { key: string; dir: "asc" | "desc" } | null;

function isNumericColumn(col: DataColumn, rows: DataRow[]): boolean {
	if (col.numeric !== undefined) return col.numeric;
	return rows.every((r) => {
		const v = r[col.key];
		return v === undefined || v === "" || typeof v === "number";
	});
}

export default function DataTable({
	columns,
	rows,
	caption,
	sortable = true,
	compact = false,
	bare = false,
}: DataTableProps) {
	const [sort, setSort] = useState<SortState>(null);

	const numericCols = useMemo(
		() => new Set(columns.filter((c) => isNumericColumn(c, rows)).map((c) => c.key)),
		[columns, rows],
	);

	const sortedRows = useMemo(() => {
		if (!sort) return rows;
		const numeric = numericCols.has(sort.key);
		const factor = sort.dir === "asc" ? 1 : -1;
		return [...rows].sort((a, b) => {
			const av = a[sort.key];
			const bv = b[sort.key];
			if (av === undefined) return 1;
			if (bv === undefined) return -1;
			if (numeric) return (Number(av) - Number(bv)) * factor;
			return String(av).localeCompare(String(bv)) * factor;
		});
	}, [rows, sort, numericCols]);

	const toggleSort = (key: string) => {
		setSort((prev) => {
			if (!prev || prev.key !== key) return { key, dir: "asc" };
			if (prev.dir === "asc") return { key, dir: "desc" };
			return null; // third click clears, restoring source order
		});
	};

	const renderCell = (col: DataColumn, value: string | number | undefined) => {
		if (value === undefined || value === "") return "—";
		if (col.format) return col.format(value);
		if (numericCols.has(col.key) && typeof value === "number") return formatNumber(value);
		return value;
	};

	return (
		<div className={`dtable-wrap not-prose${bare ? " dtable-wrap--bare" : ""}`}>
			<div className="dtable-scroll">
				<table className={`dtable${compact ? " dtable--compact" : ""}`}>
					{caption && <caption className="dtable-caption">{caption}</caption>}
					<thead>
						<tr>
							{columns.map((col) => {
								const align = col.align ?? (numericCols.has(col.key) ? "right" : "left");
								const active = sort?.key === col.key;
								const ariaSort = active
									? sort?.dir === "asc"
										? "ascending"
										: "descending"
									: "none";
								return (
									<th
										key={col.key}
										scope="col"
										aria-sort={sortable ? ariaSort : undefined}
										style={{ textAlign: align }}
									>
										{sortable ? (
											<button
												type="button"
												className={`dtable-sort${active ? " is-active" : ""}`}
												onClick={() => toggleSort(col.key)}
											>
												<span>{col.label}</span>
												<span className="dtable-sort-icon" aria-hidden="true">
													{active ? (sort?.dir === "asc" ? "▲" : "▼") : "↕"}
												</span>
											</button>
										) : (
											col.label
										)}
									</th>
								);
							})}
						</tr>
					</thead>
					<tbody>
						{sortedRows.map((row, i) => (
							<tr key={i}>
								{columns.map((col) => {
									const align = col.align ?? (numericCols.has(col.key) ? "right" : "left");
									return (
										<td key={col.key} style={{ textAlign: align }}>
											{renderCell(col, row[col.key])}
										</td>
									);
								})}
							</tr>
						))}
					</tbody>
				</table>
			</div>
		</div>
	);
}

// src/components/blog/DataTable.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { type DataColumn, type DataRow, formatNumber } from "./chartData";

const props = withDefaults(
	defineProps<{
		columns: DataColumn[];
		rows: DataRow[];
		caption?: string;
		sortable?: boolean;
		compact?: boolean;
		/** Drop the outer card chrome (used when embedded under a chart). */
		bare?: boolean;
	}>(),
	{ sortable: true, compact: false, bare: false },
);

type SortState = { key: string; dir: "asc" | "desc" } | null;
const sort = ref<SortState>(null);

function isNumericColumn(col: DataColumn): boolean {
	if (col.numeric !== undefined) return col.numeric;
	return props.rows.every((r) => {
		const v = r[col.key];
		return v === undefined || v === "" || typeof v === "number";
	});
}

const numericCols = computed(
	() => new Set(props.columns.filter(isNumericColumn).map((c) => c.key)),
);

const sortedRows = computed(() => {
	const s = sort.value;
	if (!s) return props.rows;
	const numeric = numericCols.value.has(s.key);
	const factor = s.dir === "asc" ? 1 : -1;
	return [...props.rows].sort((a, b) => {
		const av = a[s.key];
		const bv = b[s.key];
		if (av === undefined) return 1;
		if (bv === undefined) return -1;
		if (numeric) return (Number(av) - Number(bv)) * factor;
		return String(av).localeCompare(String(bv)) * factor;
	});
});

function toggleSort(key: string) {
	const prev = sort.value;
	if (!prev || prev.key !== key) sort.value = { key, dir: "asc" };
	else if (prev.dir === "asc") sort.value = { key, dir: "desc" };
	else sort.value = null; // third click clears, restoring source order
}

function alignFor(col: DataColumn): "left" | "right" | "center" {
	return col.align ?? (numericCols.value.has(col.key) ? "right" : "left");
}

function ariaSortFor(col: DataColumn): "ascending" | "descending" | "none" {
	if (sort.value?.key !== col.key) return "none";
	return sort.value.dir === "asc" ? "ascending" : "descending";
}

function renderCell(col: DataColumn, value: string | number | undefined): string | number {
	if (value === undefined || value === "") return "—";
	if (col.format) return col.format(value);
	if (numericCols.value.has(col.key) && typeof value === "number") return formatNumber(value);
	return value;
}
</script>

<template>
	<div :class="['dtable-wrap', 'not-prose', { 'dtable-wrap--bare': bare }]">
		<div class="dtable-scroll">
			<table :class="['dtable', { 'dtable--compact': compact }]">
				<caption v-if="caption" class="dtable-caption">{{ caption }}</caption>
				<thead>
					<tr>
						<th
							v-for="col in columns"
							:key="col.key"
							scope="col"
							:aria-sort="sortable ? ariaSortFor(col) : undefined"
							:style="{ textAlign: alignFor(col) }"
						>
							<button
								v-if="sortable"
								type="button"
								:class="['dtable-sort', { 'is-active': sort?.key === col.key }]"
								@click="toggleSort(col.key)"
							>
								<span>{{ col.label }}</span>
								<span class="dtable-sort-icon" aria-hidden="true">
									{{ sort?.key === col.key ? (sort?.dir === "asc" ? "▲" : "▼") : "↕" }}
								</span>
							</button>
							<template v-else>{{ col.label }}</template>
						</th>
					</tr>
				</thead>
				<tbody>
					<tr v-for="(row, i) in sortedRows" :key="i">
						<td v-for="col in columns" :key="col.key" :style="{ textAlign: alignFor(col) }">
							{{ renderCell(col, row[col.key]) }}
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>
